version: 2
project_name: ccgate
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: ccgate
    ldflags:
      - -s -w
      - -X main.version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
release:
  prerelease: auto
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
  use: github
  groups:
    - title: Breaking Changes
      regexp: '^.*!:'
      order: 0
    - title: Features
      regexp: '^feat'
      order: 1
    - title: Bug Fixes
      regexp: '^fix'
      order: 2
    - title: Refactoring
      regexp: '^refactor'
      order: 3
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^ci'
      - '^chore'
